### PR TITLE
Fix startup dependency check

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
ref #67

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
This might be good to go... not sure if my system is just messed up or not :-(

**Comment by NullVoxPopuli** [comment]
maybe related to how I resolved #69 ?


```
Traceback (most recent call last):
  File "startup.py", line 61, in <module>
    from gmusic.core.Core import Core
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/__init__.py", line 4, in <module>
    from gmusic.core import *
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/core/__init__.py", line 3, in <module>
    from gmusic.core.Core import Core
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/core/Core.py", line 2, in <module>
    from gmusic.player.PlayerController import PlayerController
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/player/__init__.py", line 1, in <module>
    from gmusic.player.PlayerController import PlayerController
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/player/PlayerController.py", line 4, in <module>
    from gmusic.player.Player import Player
  File "/home/lprestonsegoiii/Development/gmusic/gmusic/player/Player.py", line 3, in <module>
    import gst, gobject, thread
ImportError: No module named gst
```

**Comment by NullVoxPopuli** [comment]
I think I fixed the GST issue, but now it looks like there is no error checking on the credentials.

**Comment by NullVoxPopuli** [comment]
Actually, it's barfing on:

```
{"username": "me@gmail.com", "password": "1234"}{"username": "me@gmail.com", "password": "1234"}

```

so.... not sure how my credentials.json got turned in to that.... I guess that should be a separate PR.

So, I think this PR is good to go.

**Comment by etkirsch** [comment]
GST is still not defined... looking into it

**Comment by NullVoxPopuli** [comment]
I wonder if there is some environment thing we are missing that is going to require a condition around which gst method we use?

**Pull request merged**
